### ISSUE TITLE
Testnet bot didn't run on Epoch 212 (current)

### ISSUE THREAD

**Issue by meyerbro** [solana-labs/stake-o-matic#144]
Hello,

this is kind of an urgent issue since there's still time to prevent/fix it.

The testnet bot didn't run in this Epoch yet (212).

There's still time to fix it (14 hours for the epoch to finish).

I spoke with @t-nelson and it looks like there's an issue with it:
![image](https://user-images.githubusercontent.com/1686520/126891336-662d6934-55a1-4660-b9df-bdb44e089536.png)

**Comment by meyerbro** [comment]
https://github.com/solana-labs/stake-o-matic/wiki/Testnet
(Solana Maintainers edited this page 5 days ago)

**Comment by t-nelson** [comment]
My analysis was incorrect.  The problem is the bot not refreshing the blockhash while sending transactions.  See #143
